import os
import re
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from threading import Thread

import discord
from discord.ext import commands

TOKEN = os.getenv("DISCORD_TOKEN")
# Fixed: Using standard single character string prefix to prevent GitHub compile errors
PREFIX = "\$" 
VOUCH_CHANNEL_ID = 1555778546046206002

# Target channel IDs
CMD_CHANNEL_ID = 1555780870839861258
TICKET_CHANNEL_ID = 1555782121598095380

intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix=PREFIX, intents=intents, help_command=None)

# In-memory data storage
current_vanity = "your-vanity-here"
account_stock = []


@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} ({bot.user.id})")


# ==========================================
# 1. COMMAND: \$genaccess <vanity>
# ==========================================
@bot.command(name="genaccess")
@commands.has_permissions(administrator=True)
async def genaccess(ctx: commands.Context, vanity: str):
    """
    Usage: \$genaccess <vanity>
    Recreates the exact layout rules requested from the reference screenshot.
    """
    global current_vanity
    current_vanity = vanity

    # Match the layout look from the image layout instructions
    embed = discord.Embed(
        title="✨ How to Access Free Generator ✨",
        description=(
            "Your account has been generated successfully!\n\n"
            "Follow these simple steps to get access to the Free MCFA Generator!\n\n"
            "🔮 **Step 1**\n"
            "Set your custom status to:\n"
            f"`{current_vanity} : Free MCFA Generator`\n\n"
            "🔸 **Step 2**\n"
            f"Go to <#{CMD_CHANNEL_ID}> and type:\n"
            "`$cstatus`\n\n"
            "✅ **Step 3**\n"
            "You're done! 🎉 You now have access to the **Free Gen.**\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📣 **Important Notes**\n"
            "❌ Don't ping any staff for this.\n"
            f"🎫 Need help? <#{TICKET_CHANNEL_ID}>\n"
            "⚠️ Improper custom status = No access granted."
        ),
        color=0x2B2D31,  # Dark theme color profile
    )
    embed.set_footer(text="WitherCloud Generator")
    
    await ctx.send(embed=embed)


# ==========================================
# 2. COMMAND: \$gen
# ==========================================
@bot.command(name="gen")
async def gen(ctx: commands.Context):
    """
    Usage: \$gen
    Dispenses an account out of the system stock array to user DMs.
    """
    if ctx.channel.id != CMD_CHANNEL_ID:
        await ctx.reply(f"❌ This command can only be used in <#{CMD_CHANNEL_ID}>.", mention_author=False)
        return

    if not account_stock:
        await ctx.reply("❌ Out of stock! Please wait for an administrator to restock.", mention_author=False)
        return

    # Grab the first available account from the stock pool
    account = account_stock.pop(0)

    # Embed display styling parameters
    dm_embed = discord.Embed(
        title="Account Generated Successfully!",
        description=(
            "Your account has been generated successfully!\n\n"
            f"**Account:** ||{account}||\n\n"
            f"**Generated by:** {ctx.author.mention}\n\n"
            "Please keep your account details secure."
        ),
        color=discord.Color.green(), # Green colored response layout block
    )
    dm_embed.set_footer(text=f"Generated by {bot.user.name} • Today")

    try {
        await ctx.author.send(embed=dm_embed)
        await ctx.reply("✅ **Account generated!** Check your Direct Messages.", mention_author=False)
    except discord.Forbidden:
        # Re-add account back to pool if their DMs are completely closed
        account_stock.insert(0, account)
        await ctx.reply("❌ I couldn't DM you! Please open your server **Privacy Settings** to accept direct messages.", mention_author=False)


# ==========================================
# 3. COMMAND: \$restock (with file attachment)
# ==========================================
@bot.command(name="restock")
@commands.has_permissions(administrator=True)
async def restock(ctx: commands.Context):
    """
    Usage: \$restock (with attached file containing email:pass entries)
    Loads accounts line by line into memory.
    """
    if not ctx.message.attachments:
        await ctx.reply("❌ Please attach a `.txt` file containing your accounts.", mention_author=False)
        return

    attachment = ctx.message.attachments[0]
    if not attachment.filename.endswith(".txt"):
        await ctx.reply("❌ Invalid format! Please make sure your attachment is a pure `.txt` document file.", mention_author=False)
        return

    try:
        file_bytes = await attachment.read()
        content = file_bytes.decode("utf-8")
        
        # Parse text entries out while cleaning whitespace lines
        lines = [line.strip() for line in content.splitlines() if line.strip()]
        
        added_count = 0
        for line in lines:
            if ":" in line:
                account_stock.append(line)
                added_count += 1

        await ctx.reply(f"✅ Successfully stocked **{added_count}** accounts! Total available stock: **{len(account_stock)}**.", mention_author=False)
    except Exception as e:
        print(f"Restock error: {e}")
        await ctx.reply("❌ An unexpected error occurred while parsing the file attachment.", mention_author=False)


# Global command permission error handling hooks
@genaccess.error
@restock.error
async def admin_command_error(ctx: commands.Context, error: commands.CommandError):
    if isinstance(error, commands.MissingPermissions):
        await ctx.reply("❌ You do not have **Administrator** rights to use this system command.", mention_author=False)


# Render Web Service health endpoint.
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.end_headers()
        self.wfile.write(b"WitherCloud Generator Bot is running!")

    def log_message(self, format, *args):
        pass


def run_web_server():
    port = int(os.environ.get("PORT", "10000"))
    server = ThreadingHTTPServer(("0.0.0.0", port), HealthHandler)
    print(f"Health server listening on 0.0.0.0:{port}")
    server.serve_forever()


if not TOKEN:
    raise RuntimeError("Set the DISCORD_TOKEN environment variable before starting the bot.")

Thread(target=run_web_server, daemon=True).start()
bot.run(TOKEN)