import os
import re
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from threading import Thread

import discord
from discord.ext import commands
from discord import app_commands

TOKEN = os.getenv("DISCORD_TOKEN")
# Fixed: Using '.' prefix as requested to fix syntax warnings
PREFIX = "." 
VOUCH_CHANNEL_ID = 1555778546046206002

# Target channel configurations
CMD_CHANNEL_ID = 1555780870839861258
TICKET_CHANNEL_ID = 1555782121598095380

intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix=PREFIX, intents=intents, help_command=None)

# Dynamic state tracking storage arrays
current_vanity = "your-vanity-here"
account_stock = []


@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} ({bot.user.id})")
    try:
        synced = await bot.tree.sync()
        print(f"Successfully synced {len(synced)} slash command(s).")
    except Exception as e:
        print(f"Failed to sync slash commands: {e}")


# ==========================================
# 1. COMMAND: .genaccess <vanity>
# ==========================================
@bot.command(name="genaccess")
@commands.has_permissions(administrator=True)
async def genaccess(ctx: commands.Context, vanity: str):
    """
    Usage: .genaccess <vanity>
    Recreates the exact embed layout rules requested from the reference screenshot.
    """
    global current_vanity
    current_vanity = vanity

    embed = discord.Embed(
        title="✨ How to Access Free Generator ✨",
        description=(
            "Follow these simple steps to get access to the Free MCFA Generator!\n\n"
            "🔮 **Step 1**\n"
            "Set your custom status to:\n"
            f"`{current_vanity} : Free MCFA Generator`\n\n"
            "🔸 **Step 2**\n"
            f"Go to <#{CMD_CHANNEL_ID}> and type:\n"
            "`.cstatus`\n\n"
            "✅ **Step 3**\n"
            "You're done! 🎉 You now have access to the **Free Gen.**\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📣 **Important Notes**\n"
            "❌ Don't ping any staff for this.\n"
            f"🎫 Need help? <#{TICKET_CHANNEL_ID}>\n"
            "⚠️ Improper custom status = No access granted."
        ),
        color=0x2B2D31,  # Discord native dark layout background color value
    )
    embed.set_footer(text="WitherCloud Generator")
    
    await ctx.send(embed=embed)


# ==========================================
# 2. COMMAND: .gen
# ==========================================
@bot.command(name="gen")
async def gen(ctx: commands.Context):
    """
    Usage: .gen
    Pops the first account in the array and securely dispatches it to user DMs inside a green embed.
    """
    if ctx.channel.id != CMD_CHANNEL_ID:
        await ctx.reply(f"❌ This command can only be used in <#{CMD_CHANNEL_ID}>.", mention_author=False)
        return

    if not account_stock:
        await ctx.reply("❌ Out of stock! Please wait for an administrator to restock.", mention_author=False)
        return

    account = account_stock.pop(0)

    # Green delivery layout theme format rule
    dm_embed = discord.Embed(
        title="Account Generated Successfully!",
        description=(
            "Your account has been generated successfully!\n\n"
            f"**Account:** ||{account}||\n\n"
            f"**Generated by:** {ctx.author.mention}\n\n"
            "Please keep your account details secure."
        ),
        color=discord.Color.green(),
    )
    dm_embed.set_footer(text=f"Generated by {bot.user.name} • Today")

    try {
        await ctx.author.send(embed=dm_embed)
        await ctx.reply("✅ **Account generated!** Check your Direct Messages.", mention_author=False)
    except discord.Forbidden:
        # Re-add item back to array queue line safely if DMs block the payload packet
        account_stock.insert(0, account)
        await ctx.reply("❌ I couldn't DM you! Please unlock your server **Privacy Settings** to allow incoming member direct messages.", mention_author=False)


# ==========================================
# 3. SLASH COMMAND: /restock <file>
# ==========================================
@bot.tree.command(name="restock", description="Restock accounts via a .txt file (Format: email:pass)")
@app_commands.describe(file="Upload the accounts text file")
@app_commands.checks.has_permissions(administrator=True)
async def restock_slash(interaction: discord.Interaction, file: discord.Attachment):
    """
    Slash Command Usage: /restock [file]
    Requires Administrator permission.
    """
    await interaction.response.defer(ephemeral=True)

    if not file.filename.endswith(".txt"):
        await interaction.followup.send("❌ Invalid file format! Please upload a clean `.txt` file.", ephemeral=True)
        return

    try:
        file_bytes = await file.read()
        content = file_bytes.decode("utf-8")
        lines = [line.strip() for line in content.splitlines() if line.strip()]
        
        added_count = 0
        for line in lines:
            if ":" in line:
                account_stock.append(line)
                added_count += 1

        await interaction.followup.send(f"✅ Successfully stocked **{added_count}** accounts! Total system inventory size: **{len(account_stock)}**.", ephemeral=True)
    except Exception as e:
        print(f"Restock error: {e}")
        await interaction.followup.send("❌ An unexpected error occurred while parsing the text file.", ephemeral=True)


# Error handler for slash command permissions
@restock_slash.error
async def restock_slash_error(interaction: discord.Interaction, error: app_commands.AppCommandError):
    if isinstance(error, app_commands.MissingPermissions):
        if not interaction.response.is_done():
            await interaction.response.send_message("❌ Access Denied! This command requires **Administrator** permissions.", ephemeral=True)
        else:
            await interaction.followup.send("❌ Access Denied! This command requires **Administrator** permissions.", ephemeral=True)


@genaccess.error
async def admin_command_error(ctx: commands.Context, error: commands.CommandError):
    if isinstance(error, commands.MissingPermissions):
        await ctx.reply("❌ Access Denied! This administration routine requires **Administrator** permissions.", mention_author=False)


# Render health container server environment endpoint logic tracking values
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.end_headers()
        self.wfile.write(b"WitherCloud Generator Bot is running!")

    def log_message(self, format, *args):
        pass


def run_web_server():
    port = int(os.environ.get("PORT", "10000"))
    server = ThreadingHTTPServer(("0.0.0.0", port), HealthHandler)
    print(f"Health server listening on 0.0.0.0:{port}")
    server.serve_forever()


if not TOKEN:
    raise RuntimeError("Set the DISCORD_TOKEN environment variable before starting the bot.")

Thread(target=run_web_server, daemon=True).start()
bot.run(TOKEN)
